# Generated by Django 5.1.1 on 2024-09-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hostel_block',
            field=models.CharField(default='2', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(default='1234567890', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='room_number',
            field=models.CharField(default='301', max_length=10),
        ),
    ]
